# ---------------------------------
# 
# default dictionaries
# 
# ---------------------------------
import numpy as np

# -------------------------------
# for cases where the input climatology is
# generated by the model functions, rather than 
# defined by some input file
# 
default_main_generateClim = {
    'generate_climate_inputs': True, # [bool] True to use pyEW fxns to generate clim inputs, false to skip that

    # --- TIME GRID
    't_end': 1*365,    # [d] number of simulated days
    'dt': 1/(24*6),    # [d] time resolution
    'day1': 1,         # [d] initial doy
    
    # --- SOIL 
    'soil': "loam",    # [sand, loamy sand, sandy loam, loam, clay loam, clay]
    'Zr': 0.3,         # [m] soil depth
    'rho_bulk': 1.2*1e6,  # [g m-3] soil dry mass
    's_in': 0.5,       # [TODO ???]

    # --- SITE
    'atm_co2': 412,    # [ppm] TODO replace the CO2_atm line in Example.ipynb, adjusting for the right units
    'soil_co2': 4120,  # [ppm] TODO replace `CO2_air_in` line with this, adjusting for the right units
    'latitude': 40*np.pi/180,  # [radians]
    'albedo': 0.25,    # []
    'altitude': 33,    # [m]

    # --- ROCK APPLICATION
    'feedstock_name': 'forsterite',  # [] name of feedstock (ties to the mineral weight fractions in `constants.py`)
    'M_rock_in': 1000, # [g m-2] added rock powder amount
    'diss_f': 1,       # [] dissolution factor (tunable par..??)
    'd_in': np.array([100])*1e-6, # [m] grain diameter classes (order must correspond with `mineral`)
    'psd_perc_in': np.array([1]), # [%] diameter class weight
    'SSA_in': np.nan,  # [m2 g-1] either measured value or nan to estimate it

    # --- HYDROCLIMATE
    'raintype': 'stochastic_szn',  # ['deterministic', 'stochastic_noszn', 'stochastic_szn'] parameterization for rain formulation
    'R_tot': 1.2,      # [m yr-1] total rainfall in year
    'lamda': 0.25,     # [d-1] average rain frequency
    'wind_const': 1,   # [m s-1] constant wind speed later repeated for each time step
    'coastal': False,  # [bool] whether the site is coastal (only matters for ET0 calculation)
    'temp_av': 13,     # [degC] yearly avg temp for generating sine wave T profile
    'temp_ampl_yr': 11,# [degC] yearly amplitude of temperature
    'temp_ampl_d': 5,   # [degC] daily amplitude of temperature for setting temp_min and *_max
    # (for stochastic_szn rainfall)
    # monthly frequency of rain distribution [d-1]
    'lamda_szn': np.array([0.47, 0.47, 0.4, 0.3, 0.18, 0.11, 0.04, 0.08, 0.28, 0.37, 0.45, 0.45]), # [d^(-1)]: average rain frequency 
    # monthly precipitation amount [mm converted to m]
    'alfa_szn': 10**(-3)*np.array([15, 15, 15, 13, 8, 12, 14, 19, 18, 18, 16, 15]), # [mm converted to m]: average rain depth 

    # --- SOIL BIOGEOCHEM 
    'pH_in': 6.5,      # [] initial pH of soil water
    'Si_in': 0,        # [TODO ??] initial conc of silica in water(?)
    'CEC_tot': 20,     # [mmol_c per 100g dry soil] cation exchange capacity
    # CEC fractions
    'f_Ca_in': 0.49,   # [] frac Ca on CEC sites
    'f_Mg_in': 0.30,   # [] frac Mg on CEC sites
    'f_K_in': 0.10,    # [] frac K on CEC sites
    'f_Na_in': 0.05,   # [] frac Na on CEC sites
    'f_Al_in': 0.01,   # [] frac Al on CEC sites
    'f_H_in': 0.05,    # [] frac H on CEC sites
    # existing carbonates
    'CaCO3_in': 0,     # [g m-2] existing soil calcite content
    'MgCO3_in': 0,     # [g m-2] existing soil dolomite content

    # --- VEGETATION 
    'T_v': 100,        # [d] growth time
    'k_v': 3e3,        # [g m-2] carrying capacity
    'RAI': 10,         # [m2 m-2] root area index
    'root_d': 0.4*1e-3,  # [m] average root diameter
    'v_in_coeff': 1,   # [TODO ???] (initial vegetation carbon stock? In which case, v_in_coeff must be <= 1 to not exceed k_v carrying capacity) (just says "ic" in Example.ipynb)
    't0_v': 0,         # [d] starting day of growth

    # --- ORGANIC C RESPIRATION
    'ratio_aut_het': 1,  # [] ratio of autotrophic to heterotrophic resp
    'ADD': 1,            # [gOC m-2 d-1] added dry litter
    'SOC_perc': 0.05,    # [%] percent SOC in?

    # --- SWITCHES
    'keyword_wb': 1,   # 1 = varying soil moisture; 0 = constant soil moisture
    'keyword_add': 0,  # 1 = balance background cation+anion losses; 0 = no addition
    
    # --- UNITS
    'conv_mol': 1e6,   # convert mol to micromol
    'conv_Al': 1e3,    # conversion for Al species from mol to nanomol
}


# -------------------------------
# for cases where the input climatology is defined,
# not generated by the model functions 
# 
default_main_inputClim = {
    'generate_climate_inputs': False, # [bool] True to use pyEW fxns to generate clim inputs, false to skip that

    # --- TIME GRID (determined by input clim.)
    # --- CLIMATE INPUTS
    'sitename': "albany",  # [] name of the site to use
    'climpath': './era5/ewmodel-ready/era5_2020-01-01_2020-12-31',  # [] path to the climate file
    'climfn': 'daily.nc',  # [] name of the climate file to use
    'max_dt': 1/(24*6),    # [d] max time resolution (use native res if it's finer, otherwise interpolate to this res)
    # [ variable names ]
    'var_totals': ["total_precipitation", "evaporation", "surface_runoff",],   # [] names of variables whose units are totals per timestep (requiring conversion if we change timesteps)
    's_var': 'soilwater_m3_m3',  # [] variable name for soil water (in m3 m-3)
    'E_var': 'evaporation',      # [] variable name for evaporation (in m d-1)
    'Q_var': 'surface_runoff',   # [] variable name for surface runoff (in m)
    'rain_var': 'total_precipitation',   # [] variable name for rain
    'temp_air_var': 'temperature_c',   # [] variable name for 2m air temperature
    'temp_soil_var': 'temperature_c_soil',  # [] variable name for soil temperature
    'ET0_var': 'potential_evaporation',   # [] variable name for potential evap
    'geop_var': 'geopotential_at_surface',  # [] variable name for surface geopotential (for altitude calc)

    # --- CLIM (only used if not defined by input clim)
    'latitude': 40*np.pi/180,  # [radians]
    'albedo': 0.25,    # []
    'altitude': 33,    # [m]

    # --- SOIL 
    'soil': "loam",    # [sand, loamy sand, sandy loam, loam, clay loam, clay]
    'Zr': 0.3,         # [m] soil depth
    'rho_bulk': 1.2*1e6,  # [g m-3] soil dry mass
    's_in': 0.5,       # [TODO ???]

    # --- SITE
    'atm_co2_ppm': 412,    # [ppm] TODO replace the CO2_atm line in Example.ipynb, adjusting for the right units
    'soil_co2_ppm': 4120,  # [ppm] TODO replace `CO2_air_in` line with this, adjusting for the right units

    # --- ROCK APPLICATION
    'feedstock_name': 'forsterite',  # [] name of feedstock (ties to the mineral weight fractions in `constants.py`)
    'M_rock_in': 1000, # [g m-2] added rock powder amount
    'diss_f': 1,       # [] dissolution factor (tunable par, see Bertagni et al. 2025 (JAMES) Fig. 7)
    # TODO add a "grain_diameter_rule" parameter to tell `create_run_dict` in `singlerun_helperfxns.py`
    #      how to handle cases where `d_in` and `psd_perc_in` have len=1 but the feedstock has 
    #      more than 1 mineral (simplest rule is "constant", which could just repeat the d_in for 
    #      each mineral... but then would we have to change the weight? Not sure what the psd_perc_in does...)
    'd_in': np.array([100])*1e-6, # [m] grain diameter classes (order must correspond with `mineral`)
    'psd_perc_in': np.array([1]), # [%] diameter class weight
    'SSA_in': np.nan,  # [m2 g-1] either measured value or nan to estimate it

    # --- SOIL BIOGEOCHEM 
    'pH_in': 6.5,      # [] initial pH of soil water
    'Si_in': 0,        # [TODO ??] initial conc of silica in water(?)
    'CEC_tot': 20,     # [mmol_c per 100g dry soil] cation exchange capacity
    # CEC fractions
    'f_Ca_in': 0.49,   # [] frac Ca on CEC sites
    'f_Mg_in': 0.30,   # [] frac Mg on CEC sites
    'f_K_in': 0.10,    # [] frac K on CEC sites
    'f_Na_in': 0.05,   # [] frac Na on CEC sites
    'f_Al_in': 0.01,   # [] frac Al on CEC sites
    'f_H_in': 0.05,    # [] frac H on CEC sites
    # existing carbonates
    'CaCO3_in': 0,     # [g m-2] existing soil calcite content
    'MgCO3_in': 0,     # [g m-2] existing soil dolomite content

    # --- VEGETATION 
    'T_v': 100,        # [d] growth time
    'k_v': 3e3,        # [g m-2] carrying capacity
    'RAI': 10,         # [m2 m-2] root area index
    'root_d': 0.4*1e-3,  # [m] average root diameter
    'v_in_coeff': 1,   # [TODO ???] (just says "ic" in Example.ipynb)
    't0_v': 0,         # [d] starting day of growth

    # --- ORGANIC C RESPIRATION
    'ratio_aut_het': 1,  # [] ratio of autotrophic to heterotrophic resp
    'ADD': 1,            # [gOC m-2 d-1] added dry litter
    'SOC_perc': 0.05,    # [%] percent SOC in?

    # --- SWITCHES
    'keyword_wb': 1,   # 1 = varying soil moisture; 0 = constant soil moisture
    'keyword_add': 0,  # 1 = balance background cation+anion losses; 0 = no addition
    
    # --- UNITS
    'conv_mol': 1e6,   # convert mol to micromol
    'conv_Al': 1e3,    # conversion for Al species from mol to nanomol

    # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # --- OUTPUTS
    'outdir': "s3://carbonplan-carbon-removal/SMEW/smew_output/"
}